config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :roles
  resources :doctors
  resources :patients
  resources :hospitals
  resources :diseases
  resources :home2
  root 'home#index'

end

app/models/disease.rb
class Disease < ActiveRecord::Base
	validates_uniqueness_of :diseases_name
end

app/models/diseases.rb
class Diseases < ActiveRecord::Base
	
end

app/models/doctor.rb
class Doctor < ActiveRecord::Base

	belongs_to :user
	has_many :patients

end

app/models/hospital.rb
class Hospital < ActiveRecord::Base

	validates_uniqueness_of :hospital_name

	belongs_to :user
	has_many :doctors
	has_many :patients
	
end

app/models/patient.rb
class Patient < ActiveRecord::Base

	validates_uniqueness_of :name

	belongs_to :doctor
	
end

app/models/role.rb
class Role < ActiveRecord::Base

	belongs_to :users, :dependent => :destroy
	
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :role
  belongs_to :patient
  belongs_to :doctor

end

app/controllers/home2_controller.rb
class Home2Controller < ApplicationController
	def index
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
	end
	
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController

	def new
		@patient = Patient.new
	end

	def create
	  	@patient = Patient.new(patient_params)
	  	@patient.save
	  	redirect_to patients_path(@patient.id)
	end

	def index
	  	@patient = Patient.all
	end

	def show
		@patient = Patient.find(patient_params[:id])
	end

	def destroy
	  	@patient = Patient.find(params[:id])
	  	@patient.destroy
	  	redirect_to patients_path
	end


	def edit
      	@patient = Patient.find(params[:id])
  	end

	def update
   		@patient = Patient.find(params[:id])

       	if @patient.update_attributes(patient_params)

        	redirect_to patients_path
        	flash[:success] ='The Patient is Updated successfully!'    
   	    else
        	flash[:error] ='Missing Field'
        	redirect_to new_patient_path
    	end 
  	end
	private

	def patient_params 
	    params.require(:patient).permit(:user_id, :name, :ph_number, :address, :reason, :doctor_id, :appointment_date)
	end
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController

before_action :set_role, only: [:show, :edit, :update, :destroy]

  # GET /roles
  # GET /roles.json
  def index
    @roles = Role.all
  end

  # GET /roles/1
  # GET /roles/1.json
  def show
  end

  # GET /roles/new
  def new
    @role = Role.new
  end

  # GET /roles/1/edit
  def edit
  end

  # POST /roles
  # POST /roles.json
  def create
    @role = Role.new(role_params)

    respond_to do |format|
      if @role.save
        format.html { redirect_to @role, notice: 'Role was successfully created.' }
        format.json { render :show, status: :created, location: @role }
      else
        format.html { render :new }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /roles/1
  # PATCH/PUT /roles/1.json
  def update
    respond_to do |format|
      if @role.update(role_params)
        format.html { redirect_to @role, notice: 'Role was successfully updated.' }
        format.json { render :show, status: :ok, location: @role }
      else
        format.html { render :edit }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1
  # DELETE /roles/1.json
  def destroy
    @role.destroy
    respond_to do |format|
      format.html { redirect_to roles_url, notice: 'Role was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_role
      @role = Role.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def role_params
      params.require(:role).permit(:name, :description)
    end
	
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		@users = User.all

		respond_to do |format|
			format.html
			format.xml {render :xml => @users}
		end
	end

	def show
		@user = User.find(params[:id])

		respond_to do |format|
			format.html
			format.xml {render :xml => @user}
		end
	end
	def new
		@user = User.new

		respond_to do |format|
		format.html
		format.xml {render :xml => @user}
		end
	end

	def create  
      @user = User.new(params[:user])  
      
      respond_to do |format|  
        if @user.save  
          UserMailer.registration_confirmation(@user).deliver  
          format.html { redirect_to(@user, :notice => 'User was successfully created.') }  
          format.xml  { render :xml => @user, :status => :created, :location => @user }  
        else  
          format.html { render :action => "new" }  
          format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }  
        end  
      end  
    end  

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/aptients_helper.rb
module AptientsHelper
end

app/helpers/diseases_helper.rb
module DiseasesHelper
end

app/helpers/doctor_helper.rb
module DoctorHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/home2_helper.rb
module Home2Helper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/hospitals_helper.rb
module HospitalsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/patients/edit.html.erb
<style type="text/css">
  h1
  {
    position: absolute;
    top: 5%;
    left: 30%;
    color: red;

  }
  form
  {
    position: absolute;
    top: 15%;
    left: 20%;
    right: 35%;

  }
  body
  {
    background-image: url("http://www.psdgraphics.com/file/fresh-green-background.jpg");
    background-size: 1300px 700px;
    background-repeat: no-repeat;

  }
</style>

<h1>Editing Ptient Details</h1>
<% if flash[:error] %>
    <div class="error"><%= flash[:error] %></div>
<% end %>

<%= form_for @patient  do |f| %>
  <p>
    <%= f.label :name%><br>
    <%= f.text_field :name %>
  <p>
    <%= f.label :ph_number%><br>
    <%= f.text_field :ph_number %>
  </p>
  <p>
    <%= f.label :reason %><br>
    <%= f.date_field :reason %>
  </p>

  <p>
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </p>

  <p> 
    <%= f.label :appointment_date %><br>
    <%= f.text_field :appointment_date %>
  </p>
  <tr>
    
    <td><%= f.label :doctor %><br /></td>
    <td><%= collection_select(:patient_id, :doctor_id, Doctor.all, :id, :doctor_name)  %> </td>

  </tr>
  
  <p>
    <%= f.submit %>
  </p>

<% end %>  

app/views/patients/index.html.erb
<style type="text/css">
	h1
	{
		position: absolute;
		top: 5%;
		left: 30%;
		color: red;

	}
	form
	{
		position: absolute;
		top: 15%;
		left: 20%;
		right: 35%;

	}
	body
	{
		background-image: url("http://www.freevector.com/site_media/preview_images/FreeVector-Abstract-Spring-Background.jpg");
		background-size: 1300px 700px;
		background-repeat: no-repeat;

	}
</style>

<h1> Appointment Form </h1>
<form>
<table style="border: 1px solid black;">
	<tr>
		<th> Name </th><th/><th/><th/>
		<th> Phone_number </th><th/><th/><th/>
		<th> Doctor </th><th/><th/><th/>
		<th> Appointment Date </th><th/><th/><th/>
		<th> Action </th><th/><th/><th/>
	</tr>
	<% @patient.each do |p| %>
	
	<% 
	if !p.doctor_id.nil?
		@doctor = Doctor.where(:id=>p.doctor_id).first.doctor_name 
	end
	%> 
	<tr>
		<td> <%= p.name %> </td><td></td><td></td><td \>
		<td> <%= p.ph_number %> </td><td></td><td></td><td \>
		<td><%= @doctor  %></td><td></td><td></td><td \>
		<td><%= p.appointment_date %></td><td></td><td \><td \>
		</td>
	   <td><%= link_to "Delete", patient_path(p), method: :delete, data: { confirm:  "Are you sure!" }%></td>
	    <td><%= link_to 'Edit', edit_patient_path(p) %></td>
	</tr>
	<% end %>
</table><br/><br/>
<%= link_to "back", new_patient_path %>

app/views/patients/new.html.erb
<style type="text/css">
	
	h1
	{
		
		
		position: absolute;
		top: 5%;
		left: 30%;
		color: yellow;


	}
	form
	{
		position: absolute;
		top: 20%;
		left: 30%;
		right: 35%;

	}
	body
	{
		background-image: url("http://bestwallpaperhd.com/wp-content/uploads/2013/03/background-flowers.jpg");
		background-size: 1300px 700px;
		background-repeat: no-repeat;


	}

</style>

<h1> Patient Login Page </h1>
<%= form_for @patient do |f| %>
<table>
	
	<tr>
		<td> Patient Name </td>
		<td><%= f.text_field :name %></td>
	<tr>
		<td> Phone_number </td>
		<td><%= f.number_field :ph_number %></td>
	</tr>
	<tr><td>address</td>
		<td><%= f.text_field :address%></td>
	</tr>
	<tr>
		<td>reason</td>
		<td><%= f.text_field :reason%></td>
	<tr>
		<td> date of appointment </td>
		<td><%= date_select("patient", "appointment_date", :start_year => 2014, :end_year =>2015) %>
		</td>
		</tr>
	</tr>

	<tr>
		
		<td><%= f.label :doctor %><br /></td>
		<td><%= collection_select(:patient, :doctor_id, Doctor.all, :id, :doctor_name)  %> </td>
		
	</tr>
</table>
<%= f.submit %><br/><br/>
<%= link_to "Next", patients_path %>
<% end %>	

app/views/patients/show.html.erb
<h1>Patients Details</h1>
<p>
	<table>
		<tr>
			<td><strong>patient name</strong>
			<%= @patients.name%></td>
		</tr>
		<tr>
			<td><strong>phone_no</strong>
			<%= @patients.ph_number%></td>
		</tr>
		<tr>
			<td><strong>address</strong>
			<%= @patients.address%></td>
		</tr>
		<tr>
			<td><strong>reason</strong>
			<%= @patients.reason%></td>
		</tr>
	</table>
</p>
<tr>
	<td><%= link_to 'back', patients_path %></td>
</tr>