config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :roles
  resources :doctors
  resources :patients
  resources :hospitals
  resources :diseases
  resources :home2
  root 'home#index'

end

app/models/disease.rb
class Disease < ActiveRecord::Base
	validates_uniqueness_of :diseases_name
end

app/models/diseases.rb
class Diseases < ActiveRecord::Base
	
end

app/models/doctor.rb
class Doctor < ActiveRecord::Base

	belongs_to :user
	has_many :patients

end

app/models/hospital.rb
class Hospital < ActiveRecord::Base

	validates_uniqueness_of :hospital_name

	belongs_to :user
	has_many :doctors
	has_many :patients
	
end

app/models/patient.rb
class Patient < ActiveRecord::Base

	validates_uniqueness_of :name

	belongs_to :doctor
	
end

app/models/role.rb
class Role < ActiveRecord::Base

	belongs_to :users, :dependent => :destroy
	
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :role
  belongs_to :patient
  belongs_to :doctor

end

app/controllers/home2_controller.rb
class Home2Controller < ApplicationController
	def index
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
	end
	
end

app/controllers/hospitals_controller.rb
class HospitalsController < ApplicationController

	def new
		@hospital = Hospital.new()
	end

	def create
	  	@hospital = Hospital.new(hospital_params)
	  	@hospital.save
	  	redirect_to hospitals_path
	end

	def index
	  	@hospital = Hospital.all
	end

	def show
		@hospital = Hospital.find(params[:id])
	end

	def destroy
	  	@hospital = Hospital.find(params[:id])
	  	@hospital.destroy
	  	redirect_to hospitals_path
	end

	def edit
      	@hospital = Hospital.find(params[:id])
 	end
	
	def update
      	@hospital = Hospital.find(params[:id])

       	if @hospital.update_attributes(hospital_params)
        	redirect_to hospitals_path
        	flash[:notice] ='The Hospital is Updated successfully!'
       else
        	flash[:error] ='Missing Field'
        	redirect_to new_hospital_path
    	end 
  	end

	private

	def hospital_params 
	    params.require(:hospital).permit(:hospital_name, :hospital_address, :city, :area)
	end
	
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController

before_action :set_role, only: [:show, :edit, :update, :destroy]

  # GET /roles
  # GET /roles.json
  def index
    @roles = Role.all
  end

  # GET /roles/1
  # GET /roles/1.json
  def show
  end

  # GET /roles/new
  def new
    @role = Role.new
  end

  # GET /roles/1/edit
  def edit
  end

  # POST /roles
  # POST /roles.json
  def create
    @role = Role.new(role_params)

    respond_to do |format|
      if @role.save
        format.html { redirect_to @role, notice: 'Role was successfully created.' }
        format.json { render :show, status: :created, location: @role }
      else
        format.html { render :new }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /roles/1
  # PATCH/PUT /roles/1.json
  def update
    respond_to do |format|
      if @role.update(role_params)
        format.html { redirect_to @role, notice: 'Role was successfully updated.' }
        format.json { render :show, status: :ok, location: @role }
      else
        format.html { render :edit }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1
  # DELETE /roles/1.json
  def destroy
    @role.destroy
    respond_to do |format|
      format.html { redirect_to roles_url, notice: 'Role was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_role
      @role = Role.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def role_params
      params.require(:role).permit(:name, :description)
    end
	
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		@users = User.all

		respond_to do |format|
			format.html
			format.xml {render :xml => @users}
		end
	end

	def show
		@user = User.find(params[:id])

		respond_to do |format|
			format.html
			format.xml {render :xml => @user}
		end
	end
	def new
		@user = User.new

		respond_to do |format|
		format.html
		format.xml {render :xml => @user}
		end
	end

	def create  
      @user = User.new(params[:user])  
      
      respond_to do |format|  
        if @user.save  
          UserMailer.registration_confirmation(@user).deliver  
          format.html { redirect_to(@user, :notice => 'User was successfully created.') }  
          format.xml  { render :xml => @user, :status => :created, :location => @user }  
        else  
          format.html { render :action => "new" }  
          format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }  
        end  
      end  
    end  

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/aptients_helper.rb
module AptientsHelper
end

app/helpers/diseases_helper.rb
module DiseasesHelper
end

app/helpers/doctor_helper.rb
module DoctorHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/home2_helper.rb
module Home2Helper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/hospitals_helper.rb
module HospitalsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/hospitals/edit.html.erb
<style type="text/css">
  
  h1
  {
    
    
    position: absolute;
    top: 5%;
    left: 30%;
    color: blue;


  }
  form
  {
    position: absolute;
    top: 15%;
    left: 10%;
    right: 35%;

  }
  body
  {
    background-image: url("http://www.pulsardesktop.eu/data/media/3/Colour%20Background%20613%201248360959.jpg");
    background-size: 1300px 700px;
    background-repeat: no-repeat;


  }

</style>

<h1>Editing Hospital Details</h1>
<% if flash[:error] %>
    <div class="error"><%= flash[:error] %></div>
<% end %>

<%= form_for @hospital  do |f| %>
  <p>
    <%= f.label :hospital_name%><br>
    <%= f.text_field :hospital_name %>
  </p>
  <p>
    <%= f.label :hospital_address %><br>
    <%= f.date_field :hospital_address %>
  </p>

  <p>
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </p>

  <p>
    <%= f.label :area %><br>
    <%= f.text_field :area %>
  </p>
  
  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/hospitals/index.html.erb
<style type="text/css">
	
	h1
	{
		
		
		position: absolute;
		top: 5%;
		left: 30%;
		color: blue;


	}
	form
	{
		position: absolute;
		top: 15%;
		left: 10%;
		right: 35%;

	}
	body
	{
		background-image: url("http://www.winningthemoneygamewithike.com/wp-content/uploads/2013/06/2.jpg");
		background-size: 1300px 700px;
		background-repeat: no-repeat;


	}

</style>

<h1> welcome to hostipal list </h1>
<form>
<table style="border: 1px solid black;">
	<tr>
		<th> HospitalName </th><th /><th/>
		<th> Hospital address </th><th /><th />
		<th> city </th><th/><th/><th/>
		<th> Area </th><th /><th /><th/>
		<th> Action </th>
	</tr>
	<% @hospital.each do |d| %>
	<tr>
		<td> <%= d.hospital_name %></td><td></td><td></td>
		<td> <%= d.hospital_address %> </td><td></td><td></td>
		<td> <%= d.city %> </td><td></td><td></td><td></td>
		<td> <%= d.area %> </td><td></td><td></td>
		<td style="text-align: center;">
		<% if user_signed_in? %>
		<td><%= link_to "Delete", hospital_path(d), method: :delete, data: { confirm:  "Are you sure!" }%></td>
		<td><%= link_to 'Edit', edit_hospital_path(d) %></td>
		<% end %>
	</tr>
	<% end %>
</table><br/></br>
<% if user_signed_in? %>
<%= link_to "Back" , new_hospital_path %><br \><br \>
<% end %>
<% if !user_signed_in? %>
<%= link_to 'Previous', root_path %>
<% end %>

app/views/hospitals/new.html.erb
<style type="text/css">
	
	h1
	{
		
		
		position: absolute;
		top: 5%;
		left: 10%;
		color: black;


	}
	form
	{
		position: absolute;
		top: 20%;
		left: 10%;
		right: 35%;

	}
	body
	{
		background-image: url("http://ahdimages.com/wp-content/uploads/2014/03/photo-background-1.jpg");
		background-size: 1300px 700px;
		background-repeat: no-repeat;

	}

</style>


<h1> Hospital adding Page </h1>
<%= form_for @hospital do |f| %>
<table align="center"  cellpadding="3" cellspacing="5">
	<tr>
		<td>  Hospital Name </td>
		<td> <%= f.text_field :hospital_name %> </td>
		<tr>
		<td> Hospital address</td>
		<td><%= f.text_field :hospital_address %></td>
	</tr>
	<tr>
		<td> city </td>
		<td><%= f.text_field :city %></td>
	</tr>
	<tr>
		<td> Area </td>
		<td><%= f.text_field :area %></td>
	</tr>
</table>
<%= f.submit %><br/><br/>
<%= link_to "Next" , hospitals_path %><br/><br/>
<%= link_to "Back" , home2_index_path %>
<% end %>

app/views/hospitals/show.html.erb
<h1>Hospitals Details</h1>
<p>
	<table>
		<tr>
			<td><strong>Hospital name</strong>
			<%= @hospital.hospital_name%></td>
		</tr>
		<tr>
			<td><strong>Hospital Address</strong>
			<%= @hospital.hospital_address%></td>
		</tr>
		<tr>
			<td><strong>city</strong>
			<%= @hospital.city%></td>
		</tr>
		<tr>
			<td><strong>area</strong>
			<%= @hospital.area%></td>
		</tr>
	</table>
</p>
<tr>
	<td><%= link_to 'back', hospitals_path %></td>
</tr>