config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :roles
  resources :doctors
  resources :patients
  resources :hospitals
  resources :diseases
  resources :home2
  root 'home#index'

end

app/models/disease.rb
class Disease < ActiveRecord::Base
	validates_uniqueness_of :diseases_name
end

app/models/diseases.rb
class Diseases < ActiveRecord::Base
	
end

app/models/doctor.rb
class Doctor < ActiveRecord::Base

	belongs_to :user
	has_many :patients

end

app/models/hospital.rb
class Hospital < ActiveRecord::Base

	validates_uniqueness_of :hospital_name

	belongs_to :user
	has_many :doctors
	has_many :patients
	
end

app/models/patient.rb
class Patient < ActiveRecord::Base

	validates_uniqueness_of :name

	belongs_to :doctor
	
end

app/models/role.rb
class Role < ActiveRecord::Base

	belongs_to :users, :dependent => :destroy
	
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :role
  belongs_to :patient
  belongs_to :doctor

end

app/controllers/diseases_controller.rb
class DiseasesController < ApplicationController

	def new
		@disease = Disease.new()
	end

	def create
	 	@disease = Disease.new(diseases_params)
	  	@disease.save
	  	redirect_to diseases_path
	end

	def index
		@disease = Disease.all
	end

	def show
		@disease = Disease.find(params[:id])
	end

	def edit
      	@disease = Disease.find(params[:id])
  	end

	def update
   		@disease = Disease.find(params[:id])

       	if @disease.update_attributes(diseases_params)

        	redirect_to diseases_path
        	flash[:success] ='The Hospital is Updated successfully!'    
   	    else
        	flash[:error] ='Missing Field'
        	redirect_to new_disease_path
    	end 
  	end

	def destroy
		@disease = Disease.find(params[:id])
	  	@disease.destroy
	  	redirect_to diseases_path
	end
	
	private

	def diseases_params 
	    params.require(:disease).permit(:diseases_name, :symptoms)
	end

end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController

	def new
		@doctor = Doctor.new()
	end

	def create
	  	@doctor = Doctor.new(doctor_params)
	  	@doctor.save
	  	redirect_to doctors_path
	end

	def index
	  	@doctor = Doctor.all
	end

	def show
		@doctor = Doctor.find(doctor_params[:id])
	end

	def edit
      	@doctor = Doctor.find(params[:id])
  	end

	def update
    	@doctor = Doctor.find(params[:id])

       	if @doctor.update_attributes(doctor_params)

       		flash[:success] ='The Hospital is Updated successfully!'
        	redirect_to doctors_path
        	
       else
        	flash[:error] ='Missing Field'
        	redirect_to new_doctor_path
    	end 
  	end

	def destroy
		@doctor = Doctor.find(params[:id])
	  	@doctor.destroy
	  	redirect_to doctors_path
	end
	
	private

	def doctor_params 
	    params.require(:doctor).permit(:user_id, :doctor_name, :expertise, :experience, :email, :gender)
	end
end

app/controllers/home2_controller.rb
class Home2Controller < ApplicationController
	def index
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
	end
	
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController

before_action :set_role, only: [:show, :edit, :update, :destroy]

  # GET /roles
  # GET /roles.json
  def index
    @roles = Role.all
  end

  # GET /roles/1
  # GET /roles/1.json
  def show
  end

  # GET /roles/new
  def new
    @role = Role.new
  end

  # GET /roles/1/edit
  def edit
  end

  # POST /roles
  # POST /roles.json
  def create
    @role = Role.new(role_params)

    respond_to do |format|
      if @role.save
        format.html { redirect_to @role, notice: 'Role was successfully created.' }
        format.json { render :show, status: :created, location: @role }
      else
        format.html { render :new }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /roles/1
  # PATCH/PUT /roles/1.json
  def update
    respond_to do |format|
      if @role.update(role_params)
        format.html { redirect_to @role, notice: 'Role was successfully updated.' }
        format.json { render :show, status: :ok, location: @role }
      else
        format.html { render :edit }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1
  # DELETE /roles/1.json
  def destroy
    @role.destroy
    respond_to do |format|
      format.html { redirect_to roles_url, notice: 'Role was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_role
      @role = Role.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def role_params
      params.require(:role).permit(:name, :description)
    end
	
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		@users = User.all

		respond_to do |format|
			format.html
			format.xml {render :xml => @users}
		end
	end

	def show
		@user = User.find(params[:id])

		respond_to do |format|
			format.html
			format.xml {render :xml => @user}
		end
	end
	def new
		@user = User.new

		respond_to do |format|
		format.html
		format.xml {render :xml => @user}
		end
	end

	def create  
      @user = User.new(params[:user])  
      
      respond_to do |format|  
        if @user.save  
          UserMailer.registration_confirmation(@user).deliver  
          format.html { redirect_to(@user, :notice => 'User was successfully created.') }  
          format.xml  { render :xml => @user, :status => :created, :location => @user }  
        else  
          format.html { render :action => "new" }  
          format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }  
        end  
      end  
    end  

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/aptients_helper.rb
module AptientsHelper
end

app/helpers/diseases_helper.rb
module DiseasesHelper
end

app/helpers/doctor_helper.rb
module DoctorHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/home2_helper.rb
module Home2Helper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/hospitals_helper.rb
module HospitalsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/doctors/edit.html.erb
<style type="text/css">
  h1
  {
    position: absolute;
    top: 5%;
    left: 30%;
    color: red;

  }
  form
  {
    position: absolute;
    top: 20%;
    left: 30%;
    right: 35%;

  }
  body
  {
    background-image: url("http://www.backgroundsy.com/file/preview/user-interface-background.jpg");
    background-size: 1300px 700px;
    background-repeat: no-repeat;


  }
</style>


<h1>Editing Doctor Details</h1>
<% if flash[:error] %>
    <div class="error"><%= flash[:error] %></div>
<% end %>

<%= form_for @doctor  do |f| %>
  <p>
    <%= f.label :doctor_name%><br>
    <%= f.text_field :doctor_name %>
  <p>
    <%= f.label :expertise%><br>
    <%= f.text_field :expertise %>
  </p>
  <p>
    <%= f.label :experience %><br>
    <%= f.date_field :experience %>
  </p>

  <p>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </p>

  <p> 
    <%= f.label :gender %><br>
    <%= f.radio_button 'gender','male' %>male
    <%=f.radio_button 'gender','female'%>female
  </p>
  
  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/doctors/index.html.erb
<style type="text/css">
	h1
	{
		position: absolute;
		top: 5%;
		left: 30%;
		color: red;

	}
	form
	{
		position: absolute;
		top: 20%;
		left: 30%;
		right: 35%;

	}
	body
	{
		background-image: url("http://itsquare.pt/wp-content/uploads/2014/10/21.jpg");
		background-size: 1300px 700px;
		background-repeat: no-repeat;


	}
</style>



<h1> Number fo Patients assigned</h1>
<form>
<table style="border: 1px solid black;">
	<tr>
		<th> doctor Name </th><th></th><th></th>
		<th>No of patients</th><th></th>
		<th> Action </th>
	</tr>

	<% @doctor.each do |d| %>
	
	<tr>
		<td> <%= d.doctor_name %></td><td></td><td></td>
		
		<td > <% 
			a = Patient.where(:doctor_id => d.id)
			if !a.nil? or !a.empty?
				c = a.count
			else
				c = 0;
			end
			%><%= c %></td><td></td>
	    <td><%= link_to "Delete", doctor_path(d), method: :delete, data: { confirm:  "Are you sure!" }%></td>
	    <td><%= link_to 'Edit', edit_doctor_path(d) %></td>
	<% end %>
</table> <br/>
<%= link_to "Back", new_doctor_path %>
	

app/views/doctors/new.html.erb
<style type="text/css">
	
	h1
	{
		
		
		position: absolute;
		top: 5%;
		left: 30%;
		color: red;


	}
	form
	{
		position: absolute;
		top: 20%;
		left: 30%;
		right: 35%;

	}
	body
	{
		background-image: url("http://images.all-free-download.com/images/graphiclarge/blue_abstract_background_310971.jpg");
		background-size: 1300px 650px;
		background-repeat: no-repeat;


	}

</style>


<h1> Creating Doctors</h1>
<%= form_for @doctor do |f| %>
<table align="center"  cellpadding="3" cellspacing="5">
	<tr>
		<td>  Doctor Name </td>
		<td> <%= f.text_field :doctor_name %> </td>
	</tr>
	<tr>
		<td>specialization</td>
		<td><%= f.text_field :expertise %></td>
	</tr>
	<tr>
		<td>gender</td>
		<td><%= f.radio_button 'gender','male' %>male
		<%=f.radio_button 'gender','female'%>female</td>
	</tr>
	<tr>
		<td>Experience</td>
		<td><%= f.text_field :experience %></td>
	</tr>
	<tr>
		<td>email_id</td>
		<td><%= f.text_field :email %></td>
	</tr>
	<tr>
		<td><%= f.hidden_field :user_id, :value => current_user.id %></td>
	</tr>
</table>
<%= f.submit %><br/><br/>
<%= link_to "Next", doctors_path %>
<% end %>

app/views/doctors/show.html.erb
<h1>doctor Details</h1>
<p>
	<table>
		<tr>
			<td><strong>Doctor name</strong>
			<%= @patients.doctor_name %> </td>
		</tr>
		<tr>
			<td><strong>xpertise</strong>
			<%= @patients.xpertise%></td>
		</tr>
		<tr>
			<td><strong>experience</strong>
			<%= @patients.experience%></td>
		</tr>
		<tr>
			<td><strong>email</strong>
			<%= @patients.email%></td>
		</tr>
		<tr>
			<td><strong>gender</strong>
			<%= @patients.gender%></td>
		</tr>
	</table>
</p>
<tr>
	<td><%= link_to 'back', patients_path %></td>
</tr>