config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :roles
  resources :doctors
  resources :patients
  resources :hospitals
  resources :diseases
  resources :home2
  root 'home#index'

end

app/models/disease.rb
class Disease < ActiveRecord::Base
	validates_uniqueness_of :diseases_name
end

app/models/diseases.rb
class Diseases < ActiveRecord::Base
	
end

app/models/doctor.rb
class Doctor < ActiveRecord::Base

	belongs_to :user
	has_many :patients

end

app/models/hospital.rb
class Hospital < ActiveRecord::Base

	validates_uniqueness_of :hospital_name

	belongs_to :user
	has_many :doctors
	has_many :patients
	
end

app/models/patient.rb
class Patient < ActiveRecord::Base

	validates_uniqueness_of :name

	belongs_to :doctor
	
end

app/models/role.rb
class Role < ActiveRecord::Base

	belongs_to :users, :dependent => :destroy
	
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :role
  belongs_to :patient
  belongs_to :doctor

end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController

	def new
		@doctor = Doctor.new()
	end

	def create
	  	@doctor = Doctor.new(doctor_params)
	  	@doctor.save
	  	redirect_to doctors_path
	end

	def index
	  	@doctor = Doctor.all
	end

	def show
		@doctor = Doctor.find(doctor_params[:id])
	end

	def edit
      	@doctor = Doctor.find(params[:id])
  	end

	def update
    	@doctor = Doctor.find(params[:id])

       	if @doctor.update_attributes(doctor_params)

       		flash[:success] ='The Hospital is Updated successfully!'
        	redirect_to doctors_path
        	
       else
        	flash[:error] ='Missing Field'
        	redirect_to new_doctor_path
    	end 
  	end

	def destroy
		@doctor = Doctor.find(params[:id])
	  	@doctor.destroy
	  	redirect_to doctors_path
	end
	
	private

	def doctor_params 
	    params.require(:doctor).permit(:user_id, :doctor_name, :expertise, :experience, :email, :gender)
	end
end

app/controllers/home2_controller.rb
class Home2Controller < ApplicationController
	def index
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	def index
	end
	
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController

before_action :set_role, only: [:show, :edit, :update, :destroy]

  # GET /roles
  # GET /roles.json
  def index
    @roles = Role.all
  end

  # GET /roles/1
  # GET /roles/1.json
  def show
  end

  # GET /roles/new
  def new
    @role = Role.new
  end

  # GET /roles/1/edit
  def edit
  end

  # POST /roles
  # POST /roles.json
  def create
    @role = Role.new(role_params)

    respond_to do |format|
      if @role.save
        format.html { redirect_to @role, notice: 'Role was successfully created.' }
        format.json { render :show, status: :created, location: @role }
      else
        format.html { render :new }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /roles/1
  # PATCH/PUT /roles/1.json
  def update
    respond_to do |format|
      if @role.update(role_params)
        format.html { redirect_to @role, notice: 'Role was successfully updated.' }
        format.json { render :show, status: :ok, location: @role }
      else
        format.html { render :edit }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1
  # DELETE /roles/1.json
  def destroy
    @role.destroy
    respond_to do |format|
      format.html { redirect_to roles_url, notice: 'Role was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_role
      @role = Role.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def role_params
      params.require(:role).permit(:name, :description)
    end
	
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		@users = User.all

		respond_to do |format|
			format.html
			format.xml {render :xml => @users}
		end
	end

	def show
		@user = User.find(params[:id])

		respond_to do |format|
			format.html
			format.xml {render :xml => @user}
		end
	end
	def new
		@user = User.new

		respond_to do |format|
		format.html
		format.xml {render :xml => @user}
		end
	end

	def create  
      @user = User.new(params[:user])  
      
      respond_to do |format|  
        if @user.save  
          UserMailer.registration_confirmation(@user).deliver  
          format.html { redirect_to(@user, :notice => 'User was successfully created.') }  
          format.xml  { render :xml => @user, :status => :created, :location => @user }  
        else  
          format.html { render :action => "new" }  
          format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }  
        end  
      end  
    end  

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/aptients_helper.rb
module AptientsHelper
end

app/helpers/diseases_helper.rb
module DiseasesHelper
end

app/helpers/doctor_helper.rb
module DoctorHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/home2_helper.rb
module Home2Helper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/hospitals_helper.rb
module HospitalsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/roles/_form.html.erb
<%= form_for(@role) do |f| %>
  <% if @role.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@role.errors.count, "error") %> prohibited this role from being saved:</h2>

      <ul>
      <% @role.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
  
<% end %>

app/views/roles/edit.html.erb
<h1>Editing role</h1>

<%= render 'form' %>

<%= link_to 'Show', @role %> |
<%= link_to 'Back', roles_path %>

app/views/roles/index.html.erb
<h1>Listing roles</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @roles.each do |role| %>
      <tr>
        <td><%= role.name %></td>
        <td><%= role.description %></td>
        <td><%= link_to 'Show', role %></td>
        <td><%= link_to 'Edit', edit_role_path(role) %></td>
        <td><%= link_to 'Destroy', role, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Role', new_role_path %>

app/views/roles/new.html.erb
<h1>New role</h1>

<%= render 'form' %>

<%= link_to 'Back', roles_path %>

app/views/roles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @role.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @role.description %>
</p>

<%= link_to 'Edit', edit_role_path(@role) %> |
<%= link_to 'Back', roles_path %>